### ISSUE TITLE
RuntimeError: matrices expected, got 1D, 2D tensors

### ISSUE THREAD

**Issue by stiger104** [vy007vikas/PyTorch-ActorCriticRL#2]
```
Traceback (most recent call last):
  File "/Users/tom/PycharmProjects/PyTorch-ActorCriticRL/main.py", line 38, in <module>
    action = trainer.get_exploration_action(state)
  File "/Users/tom/PycharmProjects/PyTorch-ActorCriticRL/train.py", line 64, in get_exploration_action
    action = self.actor.forward(state).detach()
  File "/Users/tom/PycharmProjects/PyTorch-ActorCriticRL/model.py", line 94, in forward
    x = F.relu(self.fc1(state))
  File "/Library/anaconda/lib/python2.7/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/Library/anaconda/lib/python2.7/site-packages/torch/nn/modules/linear.py", line 54, in forward
    return self._backend.Linear()(input, self.weight, self.bias)
  File "/Library/anaconda/lib/python2.7/site-packages/torch/nn/_functions/linear.py", line 10, in forward
    output.addmm_(0, 1, input, weight.t())
RuntimeError: matrices expected, got 1D, 2D tensors at /Users/soumith/miniconda2/conda-bld/pytorch_1493756739997/work/torch/lib/TH/generic/THTensorMath.c:1232
```

**Comment by dragen1860** [comment]
Hi, have you solved the bug, @stiger104 . I came across the same problem.

**Comment by zhaoxuexuan** [comment]
The Pull requests "fix backward() error related to squeeze and another error with action… #3" works!

**Comment by SandPhoenixX517** [comment]
Hello guys, did you solve this error and if so do you remember how yoy did so
