### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './Models/0_actor.pt'

### ISSUE THREAD

**Issue by sayomakinwa** [vy007vikas/PyTorch-ActorCriticRL#5]
Any suggestions with this error: ?

Traceback (most recent call last):
  File "main.py", line 72, in <module>
    trainer.save_models(_ep)
  File "/home/sayomakinwa/.mujoco2/mujoco-py/PyTorch-ActorCriticRL/train.py", line 115, in save_models
    torch.save(self.target_actor.state_dict(), './Models/' + str(episode_count) + '_actor.pt')
  File "/home/sayomakinwa/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 219, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/home/sayomakinwa/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 142, in _with_file_like
    f = open(f, mode)
FileNotFoundError: [Errno 2] No such file or directory: './Models/0_actor.pt'

**Comment by sayomakinwa** [comment]
Too quick to write the issue! 
Solution: simply create a "Models" folder in the root directory
